# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfbc9642ddf1f1e289489d818f53600109a35c5f0cb41d3fde3645c584b4d424f8f777a21a9c0416c0df469bd08d70f004206fac36c14fb74e8238d4ced29dde

test:
  secret_key_base: b26dff33f5af4bcdfe39fa399ea21b62fa6a61149ad409a15b2abf3f02ded002391a78982b6bcebd32b6eff12c174cccfd58114fa2bec664d84cc5dd5b0641c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
